install:
  - [ apt install -y pkg-config build-essential autoconf bison re2c libxml2-dev libsqlite3-dev
  ./buildconf
  ./configure
  make -j4 ]

tests:
  assertStdoutEqual: "Hello World"
  execute: 
  - [ sapi/cli/php -r "echo '[[tests]]';"]
