install:
  packages:
  - [ apt install -y pkg-config build-essential autoconf bison re2c libxml2-dev libsqlite3-dev ]
  buildconf:
  - [ ./buildconf ]
  configure:
  - [ ./configure ]
  make:
  - [ make -j4 ]

tests:
  assertStdoutEqual: "Hello World"
  execute: 
  - [ sapi/cli/php -r "echo \"Hello World\";"]
